<?php

/**
 * @file
 * Servicenow install settings.
 */

/**
 * Reset user tables to pull user data on next login.
 */
function servicenow_update_9000() {
  \Drupal::database()->truncate('user__field_service_meow_affiliations')->execute();
  \Drupal::database()->truncate('user__field_user_department')->execute();
  \Drupal::database()->truncate('user__field_user_department2')->execute();
}

/**
 * Delete field_service_meow_sys_id field.
 */
function servicenow_update_9001() {
  \Drupal\field\Entity\FieldStorageConfig::loadByName('user', 'field_service_meow_uuid')->delete();
}

/**
 * Implements hook_update().
 */
function servicenow_update_9002() {
  $config = \Drupal::configFactory()->getEditable('servicenow.settings');
  $config->set('servicenow_api_prod', TRUE)->save();
}

/**
 * Delete princess list node and webforms.
 */
function servicenow_update_10001() {
  if ($node = \Drupal\node\Entity\Node::load(16699)) {
    $node->delete();
  }
  if ($webform = \Drupal\webform\Entity\Webform::load('dds_desktop_support')) {
    $webform->delete();
  }
}

/**
 * Drop the princess_list database table.
 */
function servicenow_update_10002() {
  $schema = \Drupal::database()->schema();
  if ($schema->tableExists('princess_list')) {
    $schema->dropTable('princess_list');
  }
}
